//=================== Copyright (c) 2025 Laboratory for Atmospheric and Space Physics ===================//
//
// Purpose: Pixel shader that outputs the same color as it receives.
//
// License: MIT License. See LICENSE file.
//
//=======================================================================================================//

#include "/Engine/Public/Platform.ush"

Texture2D InputTexture;
SamplerState InputSampler;

float4 MainPS(float4 UV : TEXCOORD0) : SV_Target0
{
	return InputTexture.Sample(InputSampler, UV.xy); // Return the same color
}
