//=================== Copyright (c) 2025 Laboratory for Atmospheric and Space Physics ===================//
//
// Purpose: Shader that renders distant objects as quads with Lambertian BRDF.
//
// License: MIT License. See LICENSE file.
//
//=======================================================================================================//

#include "/Engine/Public/Platform.ush"

float3 CameraPosition;
float4x4 ViewProjectionMatrix;

float InverseProjectionX; // = tan(fov_x / 2)
float InverseProjectionY; // = tan(fov_y / 2)

float InverseViewWidth;
float InverseViewHeight;

float3 SolarDirection;
float3 SolarSpectralIrradiance;

struct FDistantObject
{
	float4 WorldPosition;
	float4 Parameters;
};

StructuredBuffer<FDistantObject> DistantObjects;

struct FVSOutput
{
    float4 PositionCS : SV_Position;
    float3 Radiance   : TEXCOORD0;
};

FVSOutput MainVS(uint VertexID : SV_VertexID, uint InstanceID : SV_InstanceID)
{
    FVSOutput Out;

	FDistantObject Object = DistantObjects[InstanceID];

	float3 ObjectWorldPosition = Object.WorldPosition.xyz;
	float ObjectRadius = Object.Parameters.x;
	float GeometricAlbedo = Object.Parameters.y;

    // Transform object world position to clip space
	float4 ObjectCoordinateCS = mul(float4(ObjectWorldPosition, 1.0f), ViewProjectionMatrix);

	// Don't do anything if object is behind the camera (w <= 0)
	if (ObjectCoordinateCS.w <= 0.0f)
	{
		Out.PositionCS = float4(0.0f,0.0f,0.0f,0.0f);
		Out.Radiance = 0.0f;
		return Out;
	}

    // Compute object projected angular radius
	float3 ObjectDistanceVector = CameraPosition - ObjectWorldPosition;
	float ObjectDistanceFromCamera = length(ObjectDistanceVector);
	float ObjectAngularRadius = atan(ObjectRadius / max(ObjectDistanceFromCamera, 1e-6f));

    // Calculate pixel angular radius
	float PixelAngularRadiusX = 2.0f * InverseProjectionX * InverseViewWidth;
	float PixelAngularRadiusY = 2.0f * InverseProjectionY * InverseViewHeight;

    // Calculate how much of the pixel is covered by the object
	float ObjectAngularRadiusFractionX = ObjectAngularRadius / PixelAngularRadiusX;
	float ObjectAngularRadiusFractionY = ObjectAngularRadius / PixelAngularRadiusY;
	float Coverage = saturate(3.1415f * ObjectAngularRadiusFractionX * ObjectAngularRadiusFractionY);

	float3 SunObjectVector = SolarDirection - ObjectWorldPosition;

	float CosineLoss = max(0.0f, dot(normalize(ObjectDistanceVector), normalize(SunObjectVector)));

    // This is lambertian diffuse BRDF
    float3 Radiance = Coverage * CosineLoss * (SolarSpectralIrradiance * GeometricAlbedo) * 0.31830989f;

    Out.Radiance = Radiance;

    // Render the object as a quad

	float2 PixelSizeCS = float2(2.0f * InverseViewWidth, 2.0f * InverseViewHeight) * ObjectCoordinateCS.w;

    float2 VertexOffset = 0;

	// 2 x 2 pixels
    if (VertexID == 0) VertexOffset = float2(-1.0f, -1.0f);
    if (VertexID == 1) VertexOffset = float2( 1.0f, -1.0f);
    if (VertexID == 2) VertexOffset = float2(-1.0f,  1.0f);
    if (VertexID == 3) VertexOffset = float2( 1.0f,  1.0f);

    float2 VertexCoordinateCS = ObjectCoordinateCS + VertexOffset * PixelSizeCS;

    Out.PositionCS = float4(VertexCoordinateCS, ObjectCoordinateCS.z, ObjectCoordinateCS.w);

    return Out;
}

float4 MainPS(FVSOutput In) : SV_Target0
{
	return float4(In.Radiance, 1.0f);
}
