//=================== Copyright (c) 2025 Laboratory for Atmospheric and Space Physics ===================//
//
// Purpose: Pixel shader that uses quantum efficiency to tone-map the HDR input values to LDR.
//
// License: MIT License. See LICENSE file.
//
//=======================================================================================================//

#include "/Engine/Public/Platform.ush"

Texture2D InputTexture;
SamplerState InputSampler;

float SolidAngle; // This is in steradians
float PixelArea; // This is in m^2
float ExposureTime; // This is in seconds
float W1EnergyInverse; // These are in 1/J
float W2EnergyInverse;
float W3EnergyInverse;
float4 QuECurveR;
float4 QuECurveG;
float4 QuECurveB;
float SimpsonFactor;
float CorrectionFactor;
uint CurrentTime;
uint EnableShotNoise; // 0 or 1
float InvFullWellCapacity; // This is in # of electrons (inverse)

// RNG is a version of the process described in:
// https://developer.nvidia.com/gpugems/gpugems3/part-vi-gpu-computing/chapter-37-efficient-random-number-generation-and-application

// https://www.reedbeta.com/blog/hash-functions-for-gpu-rendering/
uint PcgHash(uint Input)
{
	uint State = Input * 747796405u + 2891336453u;
	uint Word = (State >> ((State >> 28u) + 4u) ^ State) * 277803737u;
	return (Word >> 22u) ^ Word;
}

uint CombinedTausworthe(inout uint Z, int S1, int S2, int S3, uint M)
{
	uint b = (Z << S1 ^ Z) >> S2;
	return Z = (Z & M) << S3 ^ b;
}

float UniformRNG(uint Z1, uint Z2, uint Z3, inout uint Z4)
{
	uint Step1 = CombinedTausworthe(Z1, 13, 19, 12, 4294967294u);
	uint Step2 = CombinedTausworthe(Z2, 2, 25, 4, 4294967288u);
	uint Step3 = CombinedTausworthe(Z3, 3, 11, 17, 4294967280u);
	Z4 = Z4 * 1664525 + 1013904223u;
	return 2.3283064365387e-10 * float(Step1 ^ Step2 ^ Step3 ^ Z4);
}

float2 BoxMuller(float U1, float U2)
{
	U1 = max(U1, 1e-6);
	float R = sqrt(-2 * log(U1));
	float Theta = 6.28318 * U2;
	return float2(R * sin(Theta), R * cos(Theta));
}

float3 ComputeShotNoise(uint Seed, float3 NumElectrons)
{
	uint Z1 = PcgHash(Seed + 1);
	uint Z2 = PcgHash(Seed + 2);
	uint Z3 = PcgHash(Seed + 3);
	uint Z4 = PcgHash(Seed + 4);

	float U1 = UniformRNG(Z1, Z3, Z4, Z2);
	float U2 = UniformRNG(Z2, Z3, Z1, Z4);
	float U3 = UniformRNG(Z3, Z1, Z2, Z4);
	float U4 = UniformRNG(Z4, Z3, Z1, Z2);

	float2 RandGaussian1 = BoxMuller(U1, U2);
	float2 RandGaussian2 = BoxMuller(U3, U4);

	float ShotNoiseR = RandGaussian1.x * sqrt(NumElectrons.r);
	float ShotNoiseG = RandGaussian1.y * sqrt(NumElectrons.g);
	float ShotNoiseB = RandGaussian2.x * sqrt(NumElectrons.b);

	return float3(ShotNoiseR, ShotNoiseG, ShotNoiseB);
}

float4 MainPS(float4 UV : TEXCOORD0, float4 Position : SV_Position) : SV_Target0
{
	// This is in W/m^2/nm/str
	float4 TotalRadiance = InputTexture.Sample(InputSampler, UV.xy);

	float W1Power	= SolidAngle * PixelArea * TotalRadiance.r;		// Power values are in W/nm
	float W2Power	= SolidAngle * PixelArea * TotalRadiance.g;
	float W3Power	= SolidAngle * PixelArea * TotalRadiance.b;

	float NumW1ElectronsR = W1Power * W1EnergyInverse * ExposureTime * QuECurveR.r;
	float NumW2ElectronsR = W2Power * W2EnergyInverse * ExposureTime * QuECurveR.g;
	float NumW3ElectronsR = W3Power * W3EnergyInverse * ExposureTime * QuECurveR.b;

	float NumW1ElectronsG = W1Power * W1EnergyInverse * ExposureTime * QuECurveG.r;
	float NumW2ElectronsG = W2Power * W2EnergyInverse * ExposureTime * QuECurveG.g;
	float NumW3ElectronsG = W3Power * W3EnergyInverse * ExposureTime * QuECurveG.b;

	float NumW1ElectronsB = W1Power * W1EnergyInverse * ExposureTime * QuECurveB.r;
	float NumW2ElectronsB = W2Power * W2EnergyInverse * ExposureTime * QuECurveB.g;
	float NumW3ElectronsB = W3Power * W3EnergyInverse * ExposureTime * QuECurveB.b;

	/* Approximate integration over visible spectrum using R, G, and B channels and Simpson's 1/3 rule.
	 * This is a close approximation given the QE curve shape is roughly parabolic. */
	float NumElectronsR = SimpsonFactor * (NumW1ElectronsR + 4.0f * NumW2ElectronsR + NumW3ElectronsR);
	float NumElectronsG = SimpsonFactor * (NumW1ElectronsG + 4.0f * NumW2ElectronsG + NumW3ElectronsG);
	float NumElectronsB = SimpsonFactor * (NumW1ElectronsB + 4.0f * NumW2ElectronsB + NumW3ElectronsB);

	NumElectronsR *= CorrectionFactor;
	NumElectronsG *= CorrectionFactor;
	NumElectronsB *= CorrectionFactor;

	// Compute shot noise with Gaussian approximation and add to electron count

	uint Seed = (uint(Position.x) * 1973u) ^ (uint(Position.y) * 9277u) ^ (CurrentTime * 2663u);

	float3 ShotNoise = EnableShotNoise * ComputeShotNoise(Seed, float3(NumElectronsR, NumElectronsG, NumElectronsB));

	NumElectronsR += ShotNoise.r;
	NumElectronsG += ShotNoise.g;
	NumElectronsB += ShotNoise.b;

	// Set final output color to NumElectrons / FWC clamped to [0-1]

	float3 Color = saturate(float3(NumElectronsR, NumElectronsG, NumElectronsB) * InvFullWellCapacity);

	return float4(Color, TotalRadiance.a);
}
