//=================== Copyright (c) 2025 Laboratory for Atmospheric and Space Physics ===================//
//
// Purpose: Pixel shader that uses quantum efficiency to tone-map the HDR input values to LDR.
//
// License: MIT License. See LICENSE file.
//
//=======================================================================================================//

#include "/Engine/Public/Platform.ush"
#include "/CielimShaders/RandomFuncs.ush"

Texture2D InputTexture;
SamplerState InputSampler;

float SolidAngle; // This is in steradians
float PixelArea; // This is in m^2
float ExposureTime; // This is in seconds
float Transmission1; // dimensionless (0 to 1)
float Transmission2; // dimensionless (0 to 1)
float Transmission3; // dimensionless (0 to 1)
float W1EnergyInverse; // These are in 1/J
float W2EnergyInverse;
float W3EnergyInverse;
float4 QuECurveR;
float4 QuECurveG;
float4 QuECurveB;
float SimpsonFactor;
float CorrectionFactor;
uint CurrentTime;
uint EnableShotNoise; // 0 or 1
float DarkCurrent; // electrons / second
uint DarkCurrentPattern;
float DarkCurrentLogSigma;
uint GrayscaleToggle;
float InvFullWellCapacity; // This is in # of electrons (inverse)

float4 MainPS(float4 UV : TEXCOORD0, float4 Position : SV_Position) : SV_Target0
{
	// This is in W/m^2/nm/str
	float4 TotalRadiance = InputTexture.Sample(InputSampler, UV.xy);

	float W1Power	= SolidAngle * PixelArea * Transmission1 * TotalRadiance.r;		// Power values are in W/nm
	float W2Power	= SolidAngle * PixelArea * Transmission2 * TotalRadiance.g;
	float W3Power	= SolidAngle * PixelArea * Transmission3 * TotalRadiance.b;

	float NumW1ElectronsR = W1Power * W1EnergyInverse * ExposureTime * QuECurveR.r;
	float NumW2ElectronsR = W2Power * W2EnergyInverse * ExposureTime * QuECurveR.g;
	float NumW3ElectronsR = W3Power * W3EnergyInverse * ExposureTime * QuECurveR.b;

	float NumW1ElectronsG = W1Power * W1EnergyInverse * ExposureTime * QuECurveG.r;
	float NumW2ElectronsG = W2Power * W2EnergyInverse * ExposureTime * QuECurveG.g;
	float NumW3ElectronsG = W3Power * W3EnergyInverse * ExposureTime * QuECurveG.b;

	float NumW1ElectronsB = W1Power * W1EnergyInverse * ExposureTime * QuECurveB.r;
	float NumW2ElectronsB = W2Power * W2EnergyInverse * ExposureTime * QuECurveB.g;
	float NumW3ElectronsB = W3Power * W3EnergyInverse * ExposureTime * QuECurveB.b;

	/* Approximate integration over visible spectrum using R, G, and B channels and Simpson's 1/3 rule.
	 * This is a close approximation given the QE curve shape is roughly parabolic. */
	float NumElectronsR = SimpsonFactor * (NumW1ElectronsR + 4.0f * NumW2ElectronsR + NumW3ElectronsR);
	float NumElectronsG = SimpsonFactor * (NumW1ElectronsG + 4.0f * NumW2ElectronsG + NumW3ElectronsG);
	float NumElectronsB = SimpsonFactor * (NumW1ElectronsB + 4.0f * NumW2ElectronsB + NumW3ElectronsB);

	NumElectronsR *= CorrectionFactor;
	NumElectronsG *= CorrectionFactor;
	NumElectronsB *= CorrectionFactor;

	/* Here, we add photon shot noise, dark current, and dark shot noise to the image.
	 * All of these effects can only add electrons, not subtract. */

	uint Seed1 = (uint(Position.x) * 1973u) ^ (uint(Position.y) * 9277u) ^ (CurrentTime * 2663u);
	uint Seed2 = (uint(Position.x) * 6158u) ^ (uint(Position.y) * 4986u) ^ (DarkCurrentPattern * 1654u);
	uint Seed3 = Seed2 ^ (CurrentTime * 3756u);

	float4 RandGaussians = max(ComputeRandGaussians(Seed1), 0);

	float PhotonShotNoiseR = EnableShotNoise * RandGaussians.x * sqrt(NumElectronsR);
	float PhotonShotNoiseG = EnableShotNoise * RandGaussians.y * sqrt(NumElectronsG);
	float PhotonShotNoiseB = EnableShotNoise * RandGaussians.z * sqrt(NumElectronsB);

	// We model dark current as log-normal distribution with median=DarkCurrent and sigma=DarkCurrentStdDeviation

	RandGaussians = ComputeRandGaussians(Seed2); // Dark current pattern should be fixed in time

	float TotalDarkRateR = DarkCurrent * exp(RandGaussians.x * DarkCurrentLogSigma);
	float DarkElectronsR = TotalDarkRateR * ExposureTime;

	float TotalDarkRateG = DarkCurrent * exp(RandGaussians.y * DarkCurrentLogSigma);
	float DarkElectronsG = TotalDarkRateG * ExposureTime;

	float TotalDarkRateB = DarkCurrent * exp(RandGaussians.z * DarkCurrentLogSigma);
	float DarkElectronsB = TotalDarkRateB * ExposureTime;

	RandGaussians = max(ComputeRandGaussians(Seed3), 0);

	float DarkShotNoiseR = EnableShotNoise * RandGaussians.x * sqrt(DarkElectronsR);
	float DarkShotNoiseG = EnableShotNoise * RandGaussians.y * sqrt(DarkElectronsG);
	float DarkShotNoiseB = EnableShotNoise * RandGaussians.z * sqrt(DarkElectronsB);

	NumElectronsR += PhotonShotNoiseR + DarkElectronsR + DarkShotNoiseR;
	NumElectronsG += PhotonShotNoiseG + DarkElectronsG + DarkShotNoiseG;
	NumElectronsB += PhotonShotNoiseB + DarkElectronsB + DarkShotNoiseB;

	// Set final output color to NumElectrons / FWC clamped to [0-1]

	float3 Color = float3(NumElectronsR, NumElectronsG, NumElectronsB);
	float3 Grayscale = float3(NumElectronsR, NumElectronsR, NumElectronsR); // Grayscale uses the R channel values

	float3 Final = saturate(lerp(Color, Grayscale, GrayscaleToggle) * InvFullWellCapacity);

	return float4(Final, TotalRadiance.a);
}
