//=================== Copyright (c) 2025 Laboratory for Atmospheric and Space Physics ===================//
//
// Purpose: Pixel shader that uses quantum efficiency to tone-map the HDR input values to LDR.
//
// License: MIT License. See LICENSE file.
//
//=======================================================================================================//

#include "/Engine/Public/Platform.ush"

Texture2D InputTexture;
SamplerState InputSampler;

float SolidAngle; // This is in steradians
float PixelArea; // This is in m^2
float ExposureTime; // This is in seconds
float W1EnergyInverse; // These are in 1/J
float W2EnergyInverse;
float W3EnergyInverse;
float4 QuECurveR;
float4 QuECurveG;
float4 QuECurveB;
float SimpsonFactor;
float CorrectionFactor;
float InvFullWellCapacity; // This is in # of electrons (inverse)

float4 MainPS(float4 UV : TEXCOORD0, float4 Position : SV_Position) : SV_Target0
{
	// This is in W/m^2/nm/str
	float4 TotalRadiance = InputTexture.Sample(InputSampler, UV.xy);

	float W1Power	= SolidAngle * PixelArea * TotalRadiance.r;		// Power values are in W/nm
	float W2Power	= SolidAngle * PixelArea * TotalRadiance.g;
	float W3Power	= SolidAngle * PixelArea * TotalRadiance.b;

	float NumW1ElectronsR = W1Power * W1EnergyInverse * ExposureTime * QuECurveR.r;
	float NumW2ElectronsR = W2Power * W2EnergyInverse * ExposureTime * QuECurveR.g;
	float NumW3ElectronsR = W3Power * W3EnergyInverse * ExposureTime * QuECurveR.b;

	float NumW1ElectronsG = W1Power * W1EnergyInverse * ExposureTime * QuECurveG.r;
	float NumW2ElectronsG = W2Power * W2EnergyInverse * ExposureTime * QuECurveG.g;
	float NumW3ElectronsG = W3Power * W3EnergyInverse * ExposureTime * QuECurveG.b;

	float NumW1ElectronsB = W1Power * W1EnergyInverse * ExposureTime * QuECurveB.r;
	float NumW2ElectronsB = W2Power * W2EnergyInverse * ExposureTime * QuECurveB.g;
	float NumW3ElectronsB = W3Power * W3EnergyInverse * ExposureTime * QuECurveB.b;

	/* Approximate integration over visible spectrum using R, G, and B channels and Simpson's 1/3 rule.
	 * This is a close approximation given the QE curve shape is roughly parabolic. */
	float NumElectronsR = SimpsonFactor * (NumW1ElectronsR + 4.0f * NumW2ElectronsR + NumW3ElectronsR);
	float NumElectronsG = SimpsonFactor * (NumW1ElectronsG + 4.0f * NumW2ElectronsG + NumW3ElectronsG);
	float NumElectronsB = SimpsonFactor * (NumW1ElectronsB + 4.0f * NumW2ElectronsB + NumW3ElectronsB);

	NumElectronsR *= CorrectionFactor;
	NumElectronsG *= CorrectionFactor;
	NumElectronsB *= CorrectionFactor;

	float ColorR = saturate(NumElectronsR * InvFullWellCapacity);
	float ColorG = saturate(NumElectronsG * InvFullWellCapacity);
	float ColorB = saturate(NumElectronsB * InvFullWellCapacity);

	return float4(ColorR, ColorG, ColorB, TotalRadiance.a);
}
