//=================== Copyright (c) 2025 Laboratory for Atmospheric and Space Physics ===================//
//
// Purpose: Pixel shader that adds random Gaussian noise to the image to simulate camera Read noise.
//
// License: MIT License. See LICENSE file.
//
//=======================================================================================================//

#include "/Engine/Public/Platform.ush"
#include "/CielimShaders/RandomFuncs.ush"

Texture2D InputTexture;
SamplerState InputSampler;

uint CurrentTime;
float ReadNoiseSigma;
uint GrayscaleToggle;
uint PixelDefectPattern;
float StuckPixelRate;
float DeadPixelRate;

float4 MainPS(float4 UV : TEXCOORD0, float4 Position : SV_Position) : SV_Target0
{
	float4 Color = InputTexture.Sample(InputSampler, UV.xy);

	uint Seed1 = (uint(Position.x) * 1973u) ^ (uint(Position.y) * 9277u) ^ (CurrentTime * 2663u);

	float4 RandGaussians = ComputeRandGaussians(Seed1);

	float4 ReadNoiseColor = float4(RandGaussians.x, RandGaussians.y, RandGaussians.z, 0.0f) * ReadNoiseSigma;
	float4 ReadNoiseGrayscale = float4(RandGaussians.x, RandGaussians.x, RandGaussians.x, 0.0f) * ReadNoiseSigma;

	float4 ReadNoise = lerp(ReadNoiseColor, ReadNoiseGrayscale, GrayscaleToggle);

	// Determine if the pixel should be stuck or dead

	uint Seed2 = (uint(Position.x) * 4215u) ^ (uint(Position.y) * 4891u) ^ (PixelDefectPattern * 5168u);
	uint Seed3 = (uint(Position.x) * 1658u) ^ (uint(Position.y) * 7519u) ^ (PixelDefectPattern * 3581u);

	float StuckPixel = ComputeRandUniform(Seed2);
	float DeadPixel = ComputeRandUniform(Seed3);

	if (StuckPixel < StuckPixelRate) return float4(1.0f, 1.0f, 1.0f, 1.0f);
	if (DeadPixel < DeadPixelRate)  return float4(0.0f, 0.0f, 0.0f, 1.0f);

	return saturate(Color + ReadNoise);
}
