//=================== Copyright (c) 2025 Laboratory for Atmospheric and Space Physics ===================//
//
// Purpose: Pixel shader that applies gain to the entire image.
//
// License: MIT License. See LICENSE file.
//
//=======================================================================================================//

#include "/Engine/Public/Platform.ush"

Texture2D InputTexture;
SamplerState InputSampler;

float SignalGain;

float4 MainPS(float4 UV : TEXCOORD0) : SV_Target0
{
	float4 InputColor = InputTexture.Sample(InputSampler, UV.xy);

	return float4(InputColor.rgb * SignalGain, InputColor.a);
}
