# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DiagnosticData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="DiagnosticData.proto",
    package="DiagnosticData",
    syntax="proto3",
    serialized_options=b"H\003",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x14\x44iagnosticData.proto\x12\x0e\x44iagnosticData"@\n\x0e\x44iagnosticData\x12\r\n\x05\x63ob_x\x18\x01 \x01(\x01\x12\r\n\x05\x63ob_y\x18\x02 \x01(\x01\x12\x10\n\x08\x63overage\x18\x03 \x01(\x01\x42\x02H\x03\x62\x06proto3',
)


_DIAGNOSTICDATA = _descriptor.Descriptor(
    name="DiagnosticData",
    full_name="DiagnosticData.DiagnosticData",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="cob_x",
            full_name="DiagnosticData.DiagnosticData.cob_x",
            index=0,
            number=1,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="cob_y",
            full_name="DiagnosticData.DiagnosticData.cob_y",
            index=1,
            number=2,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="coverage",
            full_name="DiagnosticData.DiagnosticData.coverage",
            index=2,
            number=3,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=40,
    serialized_end=104,
)

DESCRIPTOR.message_types_by_name["DiagnosticData"] = _DIAGNOSTICDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiagnosticData = _reflection.GeneratedProtocolMessageType(
    "DiagnosticData",
    (_message.Message,),
    {
        "DESCRIPTOR": _DIAGNOSTICDATA,
        "__module__": "DiagnosticData_pb2",
        # @@protoc_insertion_point(class_scope:DiagnosticData.DiagnosticData)
    },
)
_sym_db.RegisterMessage(DiagnosticData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
