# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imageDiagnostics.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 33, 4, "", "imageDiagnostics.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16imageDiagnostics.proto\x12\x10imageDiagnostics"[\n\x0e\x44iagnosticData\x12\r\n\x05\x63ob_x\x18\x01 \x01(\x01\x12\r\n\x05\x63ob_y\x18\x02 \x01(\x01\x12\x10\n\x08\x63overage\x18\x03 \x01(\x01\x12\x19\n\x11totalBrightPixels\x18\x04 \x01(\x05\x42\x02H\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "imageDiagnostics_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\003"
    _globals["_DIAGNOSTICDATA"]._serialized_start = 44
    _globals["_DIAGNOSTICDATA"]._serialized_end = 135
# @@protoc_insertion_point(module_scope)
