import sys
import os
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
PROTO_ROOT = Path(__file__).resolve().parent

sys.path.append(str(PROJECT_ROOT))

from vcpkg_install import get_triplet

TOP_BLOCK = r"""#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable: 4458 4702 4800)
#endif

#pragma push_macro("check")
#pragma push_macro("verify")

#undef check
#undef verify
"""

BOTTOM_BLOCK = r"""#pragma pop_macro("verify")
#pragma pop_macro("check")

#if defined(_MSC_VER)
#pragma warning(pop)
#endif
"""


# Adds header and footer to .pb.h files to fix macro collisions with Unreal and ignore Protobuf internal warnings
def patch_pb_h():
    for file in PROTO_ROOT.rglob("*.pb.h"):
        text = file.read_text(encoding="utf-8")

        if '#pragma push_macro("check")' in text:
            print(f"{file.name} has already been patched")
            continue

        lines = text.splitlines(keepends=True)

        top_index = None

        # Insert top block after header guard
        for i, line in enumerate(lines):
            if "#define" in line:
                top_index = i + 1
                break

        if top_index is None:
            print(f"Could not find top macro block insertion point in {file.name}")
            continue

        lines.insert(top_index, "\n" + TOP_BLOCK)

        bottom_index = None

        # Insert bottom block after protobuf macro undef
        for i, line in enumerate(lines):
            if "google/protobuf/port_undef.inc" in line:
                bottom_index = i + 1
                break

        if bottom_index is None:
            print(f"Could not find bottom macro block insertion point in {file.name}")
            continue

        lines.insert(bottom_index, "\n" + BOTTOM_BLOCK)

        file.write_text("".join(lines), encoding="utf-8")

        print(f"{file.name} has been patched")


# Adds header and footer to .pb.cc files to fix macro collisions with Unreal and ignore Protobuf internal warnings
def patch_pb_cc():
    for file in PROTO_ROOT.rglob("*.pb.cc"):
        text = file.read_text(encoding="utf-8")

        if '#pragma push_macro("check")' in text:
            print(f"{file.name} has already been patched")
            continue

        lines = text.splitlines(keepends=True)

        top_index = None

        # Insert top block after autogenerated comments
        for i, line in enumerate(lines):
            if "// Protobuf C++ Version:" in line:
                top_index = i + 1
                break

        if top_index is None:
            print(f"Could not find top macro block insertion point in {file.name}")
            continue

        lines.insert(top_index, "\n" + TOP_BLOCK)

        bottom_index = None

        # Insert bottom block after protobuf macro undef
        for i, line in enumerate(lines):
            if "google/protobuf/port_undef.inc" in line:
                bottom_index = i + 1
                break

        if bottom_index is None:
            print(f"Could not find bottom macro block insertion point in {file.name}")
            continue

        lines.insert(bottom_index, "\n" + BOTTOM_BLOCK)

        file.write_text("".join(lines), encoding="utf-8")

        print(f"{file.name} has been patched")


def build_proto_files():
    triplet = get_triplet()

    if "windows" in triplet:
        protoc_name = "protoc.exe"
    else:
        protoc_name = "protoc"

    protoc_exec = os.path.join(str(PROJECT_ROOT), "vcpkg_installed", triplet, "tools", "protobuf", protoc_name)

    if not os.path.exists(protoc_exec):
        raise FileNotFoundError(f"Could not find protoc executable at {protoc_exec}")

    for file in PROTO_ROOT.rglob("*.proto"):
        print(f"Building {file.name}...")

        try:
            subprocess.run(
                [
                    protoc_exec,
                    f"--proto_path={str(PROTO_ROOT)}",
                    f"--cpp_out={str(PROTO_ROOT)}",
                    f"--python_out={os.path.join(str(PROJECT_ROOT), 'Source', 'cielim-python', 'cielim')}",
                    file.name,
                ],
                check=True,
            )
        except subprocess.CalledProcessError as e:
            print(f"Protoc failed building {file.name} with exit code {e.returncode}")
            continue


if __name__ == "__main__":
    build_proto_files()
    patch_pb_h()
    patch_pb_cc()
