syntax = "proto3";
package cielimMessage;
option optimize_for = LITE_RUNTIME;

message TimeStamp{
    int64 frameNumber = 1;
    double simTimeElapsed = 2;
}

message EpochDateTime{
    int32 year = 1;
    int32 month = 2;
    int32 day = 3;
    int32 hours = 4;
    int32 minutes = 5;
    double seconds = 6;
}

message RenderingModel{
  double wavelength1 = 1; // [nm] first wavelength sample point
  double wavelength2 = 2; // [nm] second wavelength sample point
  double wavelength3 = 3; // [nm] third wavelength sample point
  double cosmicRayStdDeviation = 4; // [-] Standard deviation of cosmic ray frequency (poisson distribution)
  double strayLight = 5; // [-] Enable stray light model
  bool starField = 6; // [-] Enable star field
  string rendering = 7; // [-] Type of rendering engine to be used (Lumen, Ray tracing)
  bool enableSmear = 8; // [-] Enable effects of long exposure times
}

message PerlinNoise{
    int32 octaveCount = 1;
    double baseFrequency = 2;
    double baseAmplitude = 3;
    double persistence = 4;
}

message ReflectanceModel{
    string brdfModel = 1; // [string] Name of the BRDF model to apply (Lambertian by default)
    double isotropicScattering = 2; // [-] Isotropic scattering
    repeated double reflectanceParameters = 3; // [-] Parameter to apply to BRDF
}

message MeshModel{
    string shapeModel = 1; // [string] Name of the shape model to apply to the body (default is a sphere)
    double meanRadius = 2; // [m] Length of the mean asteroid radius
    double geometricAlbedo = 3; // [-] Geometric albedo of the celestial body
    repeated double principalAxisDistortion = 4; // Ratio distortions to apply to principal axes (none by default)
    repeated double inertialToBodyMrp = 5; // Attitude of mesh relative to inertial
    ReflectanceModel refModel = 6; // [-] reflectance model to apply
    PerlinNoise perlinNoise = 7;  //[-] Perlin noise to apply (none by default)
    double proceduralRocks = 8;  //[-] Parameter to generate procedural rocks on the base mesh (none by default)
}

//CelestialBody messages will carry position, velocity, and rotation data for all celestial bodies
message CelestialBody{
    string bodyName = 1;
    repeated double position = 2;   //SpicePlanetStateSimMsg.PositionVector
    repeated double velocity = 3;   //SpicePlanetStateSimMsg.VelocityVector
    repeated double attitude = 4;  //SpicePlanetStateSimMsg.J20002Pfix
    MeshModel model = 5; // Model for rendering
    bool centralBody = 6;  // Central body for all positions and velocities
}

//Spacecraft position, velocity, and attitude data
message Spacecraft{
    string spacecraftName = 1;
    repeated double position = 2;  //SCStatesMsg.r_BN_N
    repeated double velocity = 3;  //SCStatesMsg.v_BN_N
    repeated double attitude = 4;  //SCStatesMsg.sigma_BN
}

message QuantumEfficiency{
    double integrationWeightFactor = 1; // [-] Weight factor for integration over wavelength to obtain photo-electrons
    double redValue1 = 2; // [-] Value of the red channel Qe curve at the first wavelength sample point
    double redValue2 = 3; // [-] Value of the red channel Qe curve at the second wavelength sample point
    double redValue3 = 4; // [-] Value of the red channel Qe curve at the third wavelength sample point
    double greenValue1 = 5; // [-] Value of the green channel Qe curve at the first wavelength sample point
    double greenValue2 = 6; // [-] Value of the green channel Qe curve at the second wavelength sample point
    double greenValue3 = 7; // [-] Value of the green channel Qe curve at the third wavelength sample point
    double blueValue1 = 8; // [-] Value of the blue channel Qe curve at the first wavelength sample point
    double blueValue2 = 9; // [-] Value of the blue channel Qe curve at the second wavelength sample point
    double blueValue3 = 10; // [-] Value of the blue channel Qe curve at the third wavelength sample point
}

message LensModel{
    repeated double fieldOfView = 1;  //[deg, deg] Camera Field of View edge-to-edge
    double focalLength = 2; // [m] Camera focal length
    double pointSpreadFunction = 3; // [pix] Kernel size of gaussian psf
    double apertureRadius = 4; // [m] Aperture radius of lens
    float transmission1 = 5; // [-] Transmission rate of the lens (value between 0 and 1) for wavelength 1
    float transmission2 = 6; // [-] Transmission rate of the lens (value between 0 and 1) for wavelength 2
    float transmission3 = 7; // [-] Transmission rate of the lens (value between 0 and 1) for wavelength 3
    repeated double horizontalVignetting = 8; // [-] Polynomial coefficients to form the curve of vignetting (values between 0 and 1) as a function of horizontal distance from camera center (degrees)
    repeated double verticalVignetting = 9; // [-] Polynomial coefficients to form the curve of vignetting (values between 0 and 1) as a function of vertical distance from camera center (degrees)
    float distortionK1 = 10; // [-] Polynomial coefficients to form the curve of distortion (dimensionless)
    float distortionK2 = 11; // [-] Polynomial coefficients to form the curve of distortion (dimensionless)
    float distortionK3 = 12; // [-] Polynomial coefficients to form the curve of distortion (dimensionless)
    float distortionP1 = 13; // [-] Polynomial coefficients to form the curve of distortion (dimensionless)
    float distortionP2 = 14; // [-] Polynomial coefficients to form the curve of distortion (dimensionless)
}

message SensorModel{
    repeated int64 resolution = 1;  // [pixels, pixels] Desired image width and height
    uint64 renderRate = 2;  //[ns] Sim elapsed time between saved camera images
    double exposureTime = 3; // [s] Time with open shutter
    double readNoise = 4; // [e-] Read noise standard deviation in electrons
    bool shotNoise = 5; // [-] Model shot noise true or false
    double darkCurrent = 6; // [e-/s] Dark current variance value in electrons per second (will be multiplied by exposure time)
    double systemGain = 7; // [-] System gain between sensor current and pixel intensity
    double sensorWidth = 8; // [m] Width of sensor
    double sensorHeight = 9; // [m] Height of sensor
    double fullWellCapacity = 10; // [e-] Amount of charge that can be stored within an individual pixel
    double gamma = 11; // [-] Gamma correction factor
    QuantumEfficiency qeCurve = 12; // [-] Quantum Efficiency curve information
}

message AreaOfInterest{
    double centerX=1;  //!< [pix] x coordinate of the center of the area of interest
    double centerY=2;  //!< [pix] y coordinate of the center of the area of interest
    double width =3;  //!< [pix] Width of the area of interest
    double height =4;  //!< [pix] Height of the area of interest
    double threshold = 5;  //!< [0-255] threshold for a bright pixel to count (values below threshold are zeroed)
}

message ImageFormat{
    enum Format {
        PNG = 0;
        RAW_8 = 1;
        RAW_12 = 2;
        RAW_12_PACKED = 3;
        RAW_16 = 4;
    };
    Format format = 1; // [-] Image format of the received image
}

//Camera parameters
message CameraModel{
    int64 cameraId = 1;  //[-] ID of the camera
    string parentName = 2;  //[-] Name of the parent body to which the camera is attached
    repeated double cameraPositionInBody = 3;  //[m] Camera position in body frame
    repeated double bodyFrameToCameraMrp = 4;  //[-] Rotation to the camera frame MRP
    LensModel lensModel = 5; // [-] Parameters to model the optics of the camera
    SensorModel sensorModel = 6; // [-] Parameters to model the camera sensor
    AreaOfInterest areaOfInterest = 7; // [-] Sub-fov of interest for diagnostics
    ImageFormat imageFormat = 8; // [-] Output data format (PNG or RAW with specified bit depth)
}

// Cielim Message containing relevant data for image generation
message CielimMessage{
    EpochDateTime epoch = 1;
    TimeStamp currentTime = 2;
    RenderingModel renderParameters = 3; // [-] Global rendering information
    repeated CelestialBody celestialBodies = 4;
    Spacecraft spacecraft = 5;
    CameraModel camera = 6;
}
