// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiagnosticData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DiagnosticData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DiagnosticData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DiagnosticData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DiagnosticData_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace DiagnosticData {
class DiagnosticData;
struct DiagnosticDataDefaultTypeInternal;
extern DiagnosticDataDefaultTypeInternal _DiagnosticData_default_instance_;
}  // namespace DiagnosticData
PROTOBUF_NAMESPACE_OPEN
template<> ::DiagnosticData::DiagnosticData* Arena::CreateMaybeMessage<::DiagnosticData::DiagnosticData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace DiagnosticData {

// ===================================================================

class DiagnosticData final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:DiagnosticData.DiagnosticData) */ {
 public:
  inline DiagnosticData() : DiagnosticData(nullptr) {}
  ~DiagnosticData() override;
  explicit constexpr DiagnosticData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DiagnosticData(const DiagnosticData& from);
  DiagnosticData(DiagnosticData&& from) noexcept
    : DiagnosticData() {
    *this = ::std::move(from);
  }

  inline DiagnosticData& operator=(const DiagnosticData& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiagnosticData& operator=(DiagnosticData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const DiagnosticData& default_instance() {
    return *internal_default_instance();
  }
  static inline const DiagnosticData* internal_default_instance() {
    return reinterpret_cast<const DiagnosticData*>(
               &_DiagnosticData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DiagnosticData& a, DiagnosticData& b) {
    a.Swap(&b);
  }
  inline void Swap(DiagnosticData* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiagnosticData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DiagnosticData* New() const final {
    return new DiagnosticData();
  }

  DiagnosticData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DiagnosticData>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const DiagnosticData& from);
  void MergeFrom(const DiagnosticData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DiagnosticData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DiagnosticData.DiagnosticData";
  }
  protected:
  explicit DiagnosticData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCobXFieldNumber = 1,
    kCobYFieldNumber = 2,
  };
  // double cob_x = 1;
  void clear_cob_x();
  double cob_x() const;
  void set_cob_x(double value);
  private:
  double _internal_cob_x() const;
  void _internal_set_cob_x(double value);
  public:

  // double cob_y = 2;
  void clear_cob_y();
  double cob_y() const;
  void set_cob_y(double value);
  private:
  double _internal_cob_y() const;
  void _internal_set_cob_y(double value);
  public:

  // @@protoc_insertion_point(class_scope:DiagnosticData.DiagnosticData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double cob_x_;
  double cob_y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_DiagnosticData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DiagnosticData

// double cob_x = 1;
inline void DiagnosticData::clear_cob_x() {
  cob_x_ = 0;
}
inline double DiagnosticData::_internal_cob_x() const {
  return cob_x_;
}
inline double DiagnosticData::cob_x() const {
  // @@protoc_insertion_point(field_get:DiagnosticData.DiagnosticData.cob_x)
  return _internal_cob_x();
}
inline void DiagnosticData::_internal_set_cob_x(double value) {
  
  cob_x_ = value;
}
inline void DiagnosticData::set_cob_x(double value) {
  _internal_set_cob_x(value);
  // @@protoc_insertion_point(field_set:DiagnosticData.DiagnosticData.cob_x)
}

// double cob_y = 2;
inline void DiagnosticData::clear_cob_y() {
  cob_y_ = 0;
}
inline double DiagnosticData::_internal_cob_y() const {
  return cob_y_;
}
inline double DiagnosticData::cob_y() const {
  // @@protoc_insertion_point(field_get:DiagnosticData.DiagnosticData.cob_y)
  return _internal_cob_y();
}
inline void DiagnosticData::_internal_set_cob_y(double value) {
  
  cob_y_ = value;
}
inline void DiagnosticData::set_cob_y(double value) {
  _internal_set_cob_y(value);
  // @@protoc_insertion_point(field_set:DiagnosticData.DiagnosticData.cob_y)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace DiagnosticData

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DiagnosticData_2eproto
