// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiagnosticData.proto

#include "DiagnosticData.pb.h"

#include <algorithm>

/* It is necessary to silence these errors as MSVC will not build the project
   and these warnings are generated in the protobuf headers themselves. */

#if PLATFORM_WINDOWS
#pragma warning(push)
#pragma warning(disable : 4800) // Disable warning C4800
#pragma warning(disable : 4125)
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace DiagnosticData {
constexpr DiagnosticData::DiagnosticData(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : cob_x_(0)
  , cob_y_(0){}
struct DiagnosticDataDefaultTypeInternal {
  constexpr DiagnosticDataDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~DiagnosticDataDefaultTypeInternal() {}
  union {
    DiagnosticData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT DiagnosticDataDefaultTypeInternal _DiagnosticData_default_instance_;
}  // namespace DiagnosticData
namespace DiagnosticData {

// ===================================================================

class DiagnosticData::_Internal {
 public:
};

DiagnosticData::DiagnosticData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:DiagnosticData.DiagnosticData)
}
DiagnosticData::DiagnosticData(const DiagnosticData& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&cob_x_, &from.cob_x_,
    static_cast<size_t>(reinterpret_cast<char*>(&cob_y_) -
    reinterpret_cast<char*>(&cob_x_)) + sizeof(cob_y_));
  // @@protoc_insertion_point(copy_constructor:DiagnosticData.DiagnosticData)
}

void DiagnosticData::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&cob_x_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&cob_y_) -
    reinterpret_cast<char*>(&cob_x_)) + sizeof(cob_y_));
}

DiagnosticData::~DiagnosticData() {
  // @@protoc_insertion_point(destructor:DiagnosticData.DiagnosticData)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

inline void DiagnosticData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DiagnosticData::ArenaDtor(void* object) {
  DiagnosticData* _this = reinterpret_cast< DiagnosticData* >(object);
  (void)_this;
}
void DiagnosticData::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DiagnosticData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DiagnosticData::Clear() {
// @@protoc_insertion_point(message_clear_start:DiagnosticData.DiagnosticData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&cob_x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cob_y_) -
      reinterpret_cast<char*>(&cob_x_)) + sizeof(cob_y_));
  _internal_metadata_.Clear<std::string>();
}

const char* DiagnosticData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double cob_x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          cob_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double cob_y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          cob_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DiagnosticData::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DiagnosticData.DiagnosticData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double cob_x = 1;
  if (!(this->_internal_cob_x() <= 0 && this->_internal_cob_x() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_cob_x(), target);
  }

  // double cob_y = 2;
  if (!(this->_internal_cob_y() <= 0 && this->_internal_cob_y() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_cob_y(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DiagnosticData.DiagnosticData)
  return target;
}

size_t DiagnosticData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DiagnosticData.DiagnosticData)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double cob_x = 1;
  if (!(this->_internal_cob_x() <= 0 && this->_internal_cob_x() >= 0)) {
    total_size += 1 + 8;
  }

  // double cob_y = 2;
  if (!(this->_internal_cob_y() <= 0 && this->_internal_cob_y() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DiagnosticData::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const DiagnosticData*>(
      &from));
}

void DiagnosticData::MergeFrom(const DiagnosticData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DiagnosticData.DiagnosticData)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from._internal_cob_x() <= 0 && from._internal_cob_x() >= 0)) {
    _internal_set_cob_x(from._internal_cob_x());
  }
  if (!(from._internal_cob_y() <= 0 && from._internal_cob_y() >= 0)) {
    _internal_set_cob_y(from._internal_cob_y());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void DiagnosticData::CopyFrom(const DiagnosticData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DiagnosticData.DiagnosticData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiagnosticData::IsInitialized() const {
  return true;
}

void DiagnosticData::InternalSwap(DiagnosticData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DiagnosticData, cob_y_)
      + sizeof(DiagnosticData::cob_y_)
      - PROTOBUF_FIELD_OFFSET(DiagnosticData, cob_x_)>(
          reinterpret_cast<char*>(&cob_x_),
          reinterpret_cast<char*>(&other->cob_x_));
}

std::string DiagnosticData::GetTypeName() const {
  return "DiagnosticData.DiagnosticData";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace DiagnosticData
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::DiagnosticData::DiagnosticData* Arena::CreateMaybeMessage< ::DiagnosticData::DiagnosticData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DiagnosticData::DiagnosticData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
