// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: imageDiagnostics.proto
// Protobuf C++ Version: 6.33.4

#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable: 4458 4702 4800)
#endif

#pragma push_macro("check")
#pragma push_macro("verify")

#undef check
#undef verify

#include "imageDiagnostics.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace imageDiagnostics {

inline constexpr DiagnosticData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        cob_x_{0},
        cob_y_{0},
        coverage_{0},
        totalbrightpixels_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DiagnosticData::DiagnosticData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(DiagnosticData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DiagnosticDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DiagnosticDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DiagnosticDataDefaultTypeInternal() {}
  union {
    DiagnosticData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DiagnosticDataDefaultTypeInternal _DiagnosticData_default_instance_;
}  // namespace imageDiagnostics
namespace imageDiagnostics {
// ===================================================================

class DiagnosticData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<DiagnosticData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_._has_bits_);
};

DiagnosticData::DiagnosticData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, DiagnosticData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:imageDiagnostics.DiagnosticData)
}
DiagnosticData::DiagnosticData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DiagnosticData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, DiagnosticData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE DiagnosticData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void DiagnosticData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, cob_x_),
           0,
           offsetof(Impl_, totalbrightpixels_) -
               offsetof(Impl_, cob_x_) +
               sizeof(Impl_::totalbrightpixels_));
}
DiagnosticData::~DiagnosticData() {
  // @@protoc_insertion_point(destructor:imageDiagnostics.DiagnosticData)
  SharedDtor(*this);
}
inline void DiagnosticData::SharedDtor(MessageLite& self) {
  DiagnosticData& this_ = static_cast<DiagnosticData&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL DiagnosticData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DiagnosticData(arena);
}
constexpr auto DiagnosticData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DiagnosticData),
                                            alignof(DiagnosticData));
}
constexpr auto DiagnosticData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<32>{
      {
          &_DiagnosticData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DiagnosticData::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<DiagnosticData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DiagnosticData::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<DiagnosticData>(), &DiagnosticData::ByteSizeLong,
              &DiagnosticData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_._cached_size_),
          true,
      },
      "imageDiagnostics.DiagnosticData",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<32> DiagnosticData_class_data_ =
    DiagnosticData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
DiagnosticData::GetClassData() const {
  return DiagnosticData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
DiagnosticData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    DiagnosticData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::imageDiagnostics::DiagnosticData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 totalBrightPixels = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_.totalbrightpixels_)}},
    // double cob_x = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 0, 0,
      PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_.cob_x_)}},
    // double cob_y = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0,
      PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_.cob_y_)}},
    // double coverage = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 2, 0,
      PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_.coverage_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double cob_x = 1;
    {PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_.cob_x_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double cob_y = 2;
    {PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_.cob_y_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double coverage = 3;
    {PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_.coverage_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // int32 totalBrightPixels = 4;
    {PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_.totalbrightpixels_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void DiagnosticData::Clear() {
// @@protoc_insertion_point(message_clear_start:imageDiagnostics.DiagnosticData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    ::memset(&_impl_.cob_x_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.totalbrightpixels_) -
        reinterpret_cast<char*>(&_impl_.cob_x_)) + sizeof(_impl_.totalbrightpixels_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DiagnosticData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DiagnosticData& this_ = static_cast<const DiagnosticData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DiagnosticData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DiagnosticData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:imageDiagnostics.DiagnosticData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // double cob_x = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_cob_x()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          1, this_._internal_cob_x(), target);
    }
  }

  // double cob_y = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_cob_y()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_cob_y(), target);
    }
  }

  // double coverage = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_coverage()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this_._internal_coverage(), target);
    }
  }

  // int32 totalBrightPixels = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_totalbrightpixels() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_totalbrightpixels(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:imageDiagnostics.DiagnosticData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DiagnosticData::ByteSizeLong(const MessageLite& base) {
  const DiagnosticData& this_ = static_cast<const DiagnosticData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DiagnosticData::ByteSizeLong() const {
  const DiagnosticData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:imageDiagnostics.DiagnosticData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // double cob_x = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_cob_x()) != 0) {
        total_size += 9;
      }
    }
    // double cob_y = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_cob_y()) != 0) {
        total_size += 9;
      }
    }
    // double coverage = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_coverage()) != 0) {
        total_size += 9;
      }
    }
    // int32 totalBrightPixels = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_totalbrightpixels() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_totalbrightpixels());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void DiagnosticData::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<DiagnosticData*>(&to_msg);
  auto& from = static_cast<const DiagnosticData&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:imageDiagnostics.DiagnosticData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_cob_x()) != 0) {
        _this->_impl_.cob_x_ = from._impl_.cob_x_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_cob_y()) != 0) {
        _this->_impl_.cob_y_ = from._impl_.cob_y_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_coverage()) != 0) {
        _this->_impl_.coverage_ = from._impl_.coverage_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_totalbrightpixels() != 0) {
        _this->_impl_.totalbrightpixels_ = from._impl_.totalbrightpixels_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void DiagnosticData::CopyFrom(const DiagnosticData& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:imageDiagnostics.DiagnosticData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DiagnosticData::InternalSwap(DiagnosticData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_.totalbrightpixels_)
      + sizeof(DiagnosticData::_impl_.totalbrightpixels_)
      - PROTOBUF_FIELD_OFFSET(DiagnosticData, _impl_.cob_x_)>(
          reinterpret_cast<char*>(&_impl_.cob_x_),
          reinterpret_cast<char*>(&other->_impl_.cob_x_));
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace imageDiagnostics
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"

#pragma pop_macro("verify")
#pragma pop_macro("check")

#if defined(_MSC_VER)
#pragma warning(pop)
#endif
