import pytest
from typing import Generator

import cielim


def pytest_addoption(parser):
    parser.addoption(
        "--show_plots",
        action="store_true",
        default=False,
        help="Display matplotlib plots generated by tests instead of running headless.",
    )


@pytest.fixture
def show_plots(request) -> bool:
    return request.config.getoption("--show_plots")


@pytest.fixture(scope="session")
def cielim_connection() -> Generator[cielim.Connector, None, None]:
    connector: cielim.Connector = cielim.Connector()
    launcher: cielim.Launcher = cielim.Launcher()
    connector.connect(launcher.launch())
    connector.send_init_request()
    yield connector
    connector.disconnect()
    launcher.terminate()
