// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: imageDiagnostics.proto
// Protobuf C++ Version: 6.33.4

#ifndef imageDiagnostics_2eproto_2epb_2eh
#define imageDiagnostics_2eproto_2epb_2eh

#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable: 4458 4702 4800)
#endif

#pragma push_macro("check")
#pragma push_macro("verify")

#undef check
#undef verify

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_imageDiagnostics_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_imageDiagnostics_2eproto {
  static const ::uint32_t offsets[];
};
namespace imageDiagnostics {
class DiagnosticData;
struct DiagnosticDataDefaultTypeInternal;
extern DiagnosticDataDefaultTypeInternal _DiagnosticData_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<32> DiagnosticData_class_data_;
}  // namespace imageDiagnostics
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace imageDiagnostics {

// ===================================================================


// -------------------------------------------------------------------

class DiagnosticData final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:imageDiagnostics.DiagnosticData) */ {
 public:
  inline DiagnosticData() : DiagnosticData(nullptr) {}
  ~DiagnosticData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DiagnosticData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DiagnosticData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DiagnosticData(::google::protobuf::internal::ConstantInitialized);

  inline DiagnosticData(const DiagnosticData& from) : DiagnosticData(nullptr, from) {}
  inline DiagnosticData(DiagnosticData&& from) noexcept
      : DiagnosticData(nullptr, ::std::move(from)) {}
  inline DiagnosticData& operator=(const DiagnosticData& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiagnosticData& operator=(DiagnosticData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const DiagnosticData& default_instance() {
    return *reinterpret_cast<const DiagnosticData*>(
        &_DiagnosticData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DiagnosticData& a, DiagnosticData& b) { a.Swap(&b); }
  inline void Swap(DiagnosticData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiagnosticData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiagnosticData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<DiagnosticData>(arena);
  }
  void CopyFrom(const DiagnosticData& from);
  void MergeFrom(const DiagnosticData& from) { DiagnosticData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DiagnosticData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "imageDiagnostics.DiagnosticData"; }

  explicit DiagnosticData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DiagnosticData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DiagnosticData& from);
  DiagnosticData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DiagnosticData&& from) noexcept
      : DiagnosticData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCobXFieldNumber = 1,
    kCobYFieldNumber = 2,
    kCoverageFieldNumber = 3,
    kTotalBrightPixelsFieldNumber = 4,
  };
  // double cob_x = 1;
  void clear_cob_x() ;
  double cob_x() const;
  void set_cob_x(double value);

  private:
  double _internal_cob_x() const;
  void _internal_set_cob_x(double value);

  public:
  // double cob_y = 2;
  void clear_cob_y() ;
  double cob_y() const;
  void set_cob_y(double value);

  private:
  double _internal_cob_y() const;
  void _internal_set_cob_y(double value);

  public:
  // double coverage = 3;
  void clear_coverage() ;
  double coverage() const;
  void set_coverage(double value);

  private:
  double _internal_coverage() const;
  void _internal_set_coverage(double value);

  public:
  // int32 totalBrightPixels = 4;
  void clear_totalbrightpixels() ;
  ::int32_t totalbrightpixels() const;
  void set_totalbrightpixels(::int32_t value);

  private:
  ::int32_t _internal_totalbrightpixels() const;
  void _internal_set_totalbrightpixels(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:imageDiagnostics.DiagnosticData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DiagnosticData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double cob_x_;
    double cob_y_;
    double coverage_;
    ::int32_t totalbrightpixels_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_imageDiagnostics_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<32> DiagnosticData_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DiagnosticData

// double cob_x = 1;
inline void DiagnosticData::clear_cob_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cob_x_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double DiagnosticData::cob_x() const {
  // @@protoc_insertion_point(field_get:imageDiagnostics.DiagnosticData.cob_x)
  return _internal_cob_x();
}
inline void DiagnosticData::set_cob_x(double value) {
  _internal_set_cob_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:imageDiagnostics.DiagnosticData.cob_x)
}
inline double DiagnosticData::_internal_cob_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cob_x_;
}
inline void DiagnosticData::_internal_set_cob_x(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cob_x_ = value;
}

// double cob_y = 2;
inline void DiagnosticData::clear_cob_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cob_y_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double DiagnosticData::cob_y() const {
  // @@protoc_insertion_point(field_get:imageDiagnostics.DiagnosticData.cob_y)
  return _internal_cob_y();
}
inline void DiagnosticData::set_cob_y(double value) {
  _internal_set_cob_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:imageDiagnostics.DiagnosticData.cob_y)
}
inline double DiagnosticData::_internal_cob_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cob_y_;
}
inline void DiagnosticData::_internal_set_cob_y(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cob_y_ = value;
}

// double coverage = 3;
inline void DiagnosticData::clear_coverage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.coverage_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double DiagnosticData::coverage() const {
  // @@protoc_insertion_point(field_get:imageDiagnostics.DiagnosticData.coverage)
  return _internal_coverage();
}
inline void DiagnosticData::set_coverage(double value) {
  _internal_set_coverage(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:imageDiagnostics.DiagnosticData.coverage)
}
inline double DiagnosticData::_internal_coverage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.coverage_;
}
inline void DiagnosticData::_internal_set_coverage(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.coverage_ = value;
}

// int32 totalBrightPixels = 4;
inline void DiagnosticData::clear_totalbrightpixels() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.totalbrightpixels_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t DiagnosticData::totalbrightpixels() const {
  // @@protoc_insertion_point(field_get:imageDiagnostics.DiagnosticData.totalBrightPixels)
  return _internal_totalbrightpixels();
}
inline void DiagnosticData::set_totalbrightpixels(::int32_t value) {
  _internal_set_totalbrightpixels(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:imageDiagnostics.DiagnosticData.totalBrightPixels)
}
inline ::int32_t DiagnosticData::_internal_totalbrightpixels() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.totalbrightpixels_;
}
inline void DiagnosticData::_internal_set_totalbrightpixels(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.totalbrightpixels_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace imageDiagnostics


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#pragma pop_macro("verify")
#pragma pop_macro("check")

#if defined(_MSC_VER)
#pragma warning(pop)
#endif

#endif  // imageDiagnostics_2eproto_2epb_2eh
